### ISSUE TITLE
Mozilla Observatory 2.0 launching sooner or later.

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/zola-themes#4]
Mozilla Observatory 2.0 launching ~~January 25, 2024~~ ~~very soon~~ sooner or later.

Some updates will likely be necessary once it goes live.

https://developer.mozilla.org/en-US/observatory

**Comment by soumendrak** [comment]
@Jieiku 
Please update the Mozilla Observatory link to https://developer.mozilla.org/en-US/observatory

**Comment by Jieiku** [comment]
@soumendrak do you know if the new observatory code is available to run your own local copy?

I ask because it seems it is unable to scan sites in a subfolder, for example: https://welpo.github.io/tabi/

I am able to scan that same url using my locally hosted copy of the old observatory.

**Comment by soumendrak** [comment]
@Jieiku 
![image](https://github.com/user-attachments/assets/4a353f37-eb86-43ec-9ab6-a2f387adcee0)
Somehow, the site you provided is not working.
I tested with `https://www.soumendrak.com/posts/` it worked.

**Comment by Jieiku** [comment]
@soumendrak 

> Somehow, the site you provided is not working.

The reason is because the site I provided is a true subdomain as a folder path.

None of these sites work with the current observatory:

https://welpo.github.io/tabi/
https://getzola.github.io/book/
https://kuznetsov17.github.io/minimal-dark/
https://kuznetsov17.github.io/pico/
https://marcodpt.github.io/zolastrap/
https://st1020.github.io/kita/
https://getzola.github.io/after-dark/
https://cydave.github.io/zola-theme-papermod/
https://getzola.github.io/even/
https://getzola.github.io/hyde/
https://inputusername.github.io/zola-hook/
https://es-romo.github.io/coco/
https://mattyrad.github.io/soapstone/
https://gamingrobot.github.io/zallery-demo/
https://sirodoht.github.io/zola-henry/
https://pawroman.github.io/zola-theme-terminimal/
https://schoenenberg.github.io/zola-paper/

https://atgumx.gitlab.io/no-style-please/
https://versbinarii.gitlab.io/blog/

To be fair those sites also do not work with the old observatory, but they do work with my self hosted copy of the old observatory because I modified it so that it would work, it was a very small edit that was not difficult to make.

For instance these ones work https://adfaure.github.io/kodama-theme/ , https://oltdaniel.github.io/dose/

but only because they also work if you remove the subfolder: https://adfaure.github.io , https://oltdaniel.github.io

In the case of the non working sites, they only exist as subfolders. (without the subfolder they return 404 because it does not exist)

**Comment by Jieiku** [comment]
I could be totally wrong about this, but it seems like it is mostly the website part of observatory that changed, and the underlying tool is the same tool, not an entirely new codebase, so moving forward should not be too painful.
